### ISSUE TITLE
Extending configuration files is not working

### ISSUE THREAD

**Issue by heebtob** [idok/eslint-plugin#30]
We use the configuration extending feature in our project but it doesn't work in Webstorm.
http://eslint.org/docs/user-guide/configuring.html#extending-configuration-files

If we start eslint in console with npm run lint, it works.

This is our .eslintrc file
```
{
    "extends": [
        "../node_modules/conventions/.eslintrc-es6",
        "../node_modules/conventions/.eslintrc-react"
    ],
    "env": {
        "browser": true
    }
}
```

Console Output
```
"C:\Program Files (x86)\JetBrains\WebStorm 10.0.4\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\username\WebstormProjects\projectname\node_modules\eslint\bin\eslint.js --format=checkstyle client.js
C:\Users\username\WebstormProjects\projectname\node_modules\eslint\lib\config.js:129
                    throw e;
                          ^
Error: Cannot read config file: C:\Users\username\AppData\Local\Temp\-mirror-1\Users\username\WebstormProjects\projectname\node_modules\conventions\.eslintrc-react
Error: ENOENT, no such file or directory 'C:\Users\username\AppData\Local\Temp\-mirror-1\Users\username\WebstormProjects\projectname\node_modules\conventions\.eslintrc-react'
Referenced from: C:\Users\username\AppData\Local\Temp\-mirror-1\Users\username\WebstormProjects\projectname\app\.eslintrc
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at loadConfig (C:\Users\username\WebstormProjects\projectname\node_modules\eslint\lib\config.js:73:57)
    at C:\Users\username\WebstormProjects\projectname\node_modules\eslint\lib\config.js:123:46
    at Array.reduceRight (native)
    at loadConfig (C:\Users\username\WebstormProjects\projectname\node_modules\eslint\lib\config.js:111:36)
    at getLocalConfig (C:\Users\username\WebstormProjects\projectname\node_modules\eslint\lib\config.js:225:23)
    at Config.getConfig (C:\Users\username\WebstormProjects\projectname\node_modules\eslint\lib\config.js:363:22)
    at processText (C:\Users\username\WebstormProjects\projectname\node_modules\eslint\lib\cli-engine.js:183:27)

Process finished with exit code 1
```

**Comment by almilo** [comment]
Same behavior with IDEA 14.
This bug is a showstopper for using this great plugin. When having a lot of projects with same rules, 'extends' is a really cool feature.

**Comment by Cweili** [comment]
+1

**Comment by emmkong** [comment]
+1

**Comment by stephenleicht** [comment]
+1

**Comment by idok** [comment]
Are you using ESLint plugin or is it the bundled plugin?
Intellij 14 comes with a bundled eslint plugin based on this one but maintained by jetbrains.
I think the issue you are referring to exists in the bundled version and not this one.
How to check which version you have:
Open settings, if the plugin settings is under "Other Settings", it's this one, otherwise it's the bundled plugin.
![screen shot 2015-08-30 at 09 27 26](https://cloud.githubusercontent.com/assets/1866543/9566006/0e08835e-4efa-11e5-906b-e3e6769ccb90.png)

**Comment by stephenleicht** [comment]
Using your plugin instead of the bundled one works perfectly. Thanks!

**Comment by Cweili** [comment]
@idok Thanks a lot!
