### ISSUE TITLE
ESLint plugin: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by xMort** [idok/eslint-plugin#43]
Hello,

I'm running ESLint plugin in latest IntelliJ IDEA 15.0.4 on Windows with custom rules. These rules works for esLint run via gulp but do not with globally installed eslint via this plugin.

`Error running ESLint inspection: 
java.lang.NullPointerException
	at com.eslint.ESLintExternalAnnotator.doAnnotate(ESLintExternalAnnotator.java:243)
	at com.eslint.ESLintExternalAnnotator.doAnnotate(ESLintExternalAnnotator.java:52)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
`

**Comment by Freemahn** [comment]
I have same problem. A help would be appreciated.

**Comment by MichaelKapustey** [comment]
Same issue in webstorm 11.0.3

**Comment by rdmclin2** [comment]
same problem

**Comment by BernhardRode** [comment]
+1

**Comment by wondermen** [comment]
same problem on the idea14

**Comment by sskyy** [comment]
+1

**Comment by Osterjour** [comment]
Same here... As I don't have a clue about IntelliJ plugins and didn't work with JAVA for about 10 years I can't fix it myself. Is there really nobody who at least can try to fix it?

**Comment by jeanblanchard** [comment]
I had this issue too, and it was caused by dependencies missing from the global eslint install.
Running the eslint cli displayed error messages, and I'm guessing the plugin does not correctly parse error messages from the command.

So I guess the plugin should be updated to display a helpful message when the eslint command fails.

**Comment by Willibaur** [comment]
Same problem on idea14
