### ISSUE TITLE
Failed to run ESlint 

### ISSUE THREAD

**Issue by YuKaiChan** [idok/eslint-plugin#52]
I have a problem with ESlint in webstorm 

first  I npm eslint  in windows

`npm install -g eslint `

then set the path in webstorm , for example `
![1467637554](https://cloud.githubusercontent.com/assets/14308179/16561354/4fef70d2-422b-11e6-8be3-581451708359.png)

but it dose't work , the message show

```
"C:\Program Files\nodejs\node.exe" C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\bin\eslint.js --format=checkstyle --stdin --stdin-filename index.js
No ESLint configuration found.
Error: No ESLint configuration found.
    at getLocalConfig (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\config.js:168:33)
    at Config.getConfig (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\config.js:263:22)
    at processText (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:223:27)
    at CLIEngine.executeOnText (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:749:26)
    at Object.cli.execute (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\cli.js:181:36)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\bin\eslint.js:58:28
    at ConcatStream.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\node_modules\concat-stream\index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:475:14)

Process finished with exit code 0
```

I don't know how to do , that's why ? Can anybody help?

**Comment by idok** [comment]
Please read: https://github.com/idok/eslint-plugin#bundled-plugin
