### ISSUE TITLE
Error running ESLint inspection: path doesn't exist

### ISSUE THREAD

**Issue by AndyOGo** [idok/eslint-plugin#61]
```sh
Error running ESLint inspection: path doesn't exist
java.lang.IllegalArgumentException: path doesn't exist
	at com.wix.nodejs.NodeRunner.createCommandLine(NodeRunner.java:40)
	at com.eslint.utils.CliBuilder.create(CliBuilder.java:24)
	at com.eslint.utils.CliBuilder.createLint(CliBuilder.java:29)
	at com.eslint.utils.ESLintRunner.lint(ESLintRunner.java:52)
	at com.eslint.utils.ESLintRunner.lint(ESLintRunner.java:60)
	at com.eslint.ESLintExternalAnnotator.doAnnotate(ESLintExternalAnnotator.java:242)
	at com.eslint.ESLintExternalAnnotator.doAnnotate(ESLintExternalAnnotator.java:52)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: path doesn't exist
	at com.wix.nodejs.NodeRunner.createCommandLine(NodeRunner.java:40)
	at com.eslint.utils.CliBuilder.create(CliBuilder.java:24)
	at com.eslint.utils.CliBuilder.createLint(CliBuilder.java:29)
	at com.eslint.utils.ESLintRunner.lint(ESLintRunner.java:52)
	at com.eslint.utils.ESLintRunner.lint(ESLintRunner.java:60)
	at com.eslint.ESLintExternalAnnotator.doAnnotate(ESLintExternalAnnotator.java:242)
	at com.eslint.ESLintExternalAnnotator.doAnnotate(ESLintExternalAnnotator.java:52)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by superbogy** [comment]
same to me

**Comment by function-de** [comment]
same here

**Comment by ruchevits** [comment]
+1

**Comment by elzup** [comment]
I solved the same problem.
I setup both configs.
But I don't know difference between there.

![preferences_and_eslint_inspection_setting_-_google_](https://cloud.githubusercontent.com/assets/2284908/24586343/5037199e-17d9-11e7-9f20-0156613bfe46.png)

**Comment by jcrben** [comment]
I was noticing errors when running this plugin. Then I read the README more carefully and realized that ESLint is built into Intellij these days. So you might want to consider whether you really need this.

![image](https://cloud.githubusercontent.com/assets/5614134/24840028/726c2fe0-1d1a-11e7-9c45-f77402c076d1.png)

**Comment by xiaweiss** [comment]
on Version 2018.1.4.  Do not install this eslint-plugin. Just only set Enable, it will works
![2017825-webstrom-eslint](https://user-images.githubusercontent.com/17960084/43240213-fbf4b3c8-90c7-11e8-874e-be9c182ee4f9.png)
