### ISSUE TITLE
Short name 'SassLintInspection' is not unique

### ISSUE THREAD

**Issue by narration-sd** [idok/eslint-plugin#70]
I got the following in alert panes from JetBrains, just on starting after updating  your plugin last night.

Looking at what it seems to indicate, I wonder if the fact that I updated two different versions of PhpStorm (release and EAP) might be involved, via some shared-across-versions config or store?  

Is there something you need to do to assure two copies of the plugin are never installed or loaded, as other plugins don't seem to do this?

Short name 'SassLintInspection' is not unique

Short name 'SassLintInspection' is not unique
class 'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
and
class'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
conflict [Plugin: com.wix.sasslint]
com.intellij.diagnostic.PluginException: Short name 'SassLintInspection' is not unique
class 'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
and
class'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
conflict [Plugin: com.wix.sasslint]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by idok** [comment]
fixed by https://github.com/idok/sass-lint-plugin/issues/20
